### ISSUE TITLE
bad targets input results in "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by Dieterbe** [tsenart/vegeta#167]
```
~/g/s/g/r/r/inspect-es ❯❯❯ vegeta -version                                                                                                                                                   ⏎
???
```
i most likely was using cf6baac643f6b6e60cb2428d25202240ec548c8b though, just after 5.9.0

i'm running vegeta called from a script as `vegeta attack -duration 180s -rate 200
`, feeding it targets on stdin.
i introduced a bug in the script that caused it to feed "targets" like so:

```
X-Org-Id: 2

X-Org-Id: 2
```

this caused:
```
2016/01/14 18:33:01 bad method: X-Org-Id:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x63c43f]

goroutine 1 [running]:
github.com/streadway/quantile.(*Estimator).Get(0x0, 0x3fe0000000000000, 0x0)
	/home/dieter/go/src/github.com/streadway/quantile/quantile.go:141 +0x1f
github.com/tsenart/vegeta/lib.(*Metrics).Close(0xc8200a6200)
	/home/dieter/go/src/github.com/tsenart/vegeta/lib/metrics.go:137 +0x30b
main.report(0x7d1968, 0x4, 0x7d1808, 0x5, 0x7d1810, 0x6, 0x0, 0x0)
	/home/dieter/go/src/github.com/tsenart/vegeta/report.go:99 +0x9bd
main.reportCmd.func1(0xc82000a2b0, 0x0, 0x0, 0x0, 0x0)
	/home/dieter/go/src/github.com/tsenart/vegeta/report.go:21 +0xb6
main.main()
	/home/dieter/go/src/github.com/tsenart/vegeta/main.go:73 +0x909

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/lib/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/lib/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select, locked to thread]:
runtime.gopark(0x86e978, 0xc820030728, 0x7d1520, 0x6, 0x434f18, 0x2)
	/usr/lib/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820030728, 0x0, 0x18)
	/usr/lib/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820030728)
	/usr/lib/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/lib/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1696 +0x1
```

**Comment by Dieterbe** [comment]
upgraded to latest git master. cannot reproduce anymore. saw some recent commits from last november that probably fixed this case.
