### ISSUE TITLE
Crashing when using 70k req/sec

### ISSUE THREAD

**Issue by asafm** [tsenart/vegeta#197]
```
goroutine 1385672 [runnable]:
syscall.socketcall(0x2, 0x12085, 0xe65e6b28, 0x10, 0x0, 0x0, 0x0, 0xffffffff, 0x62)
       	/usr/local/Cellar/go/1.7/libexec/src/syscall/asm_linux_386.s:119 +0x5
syscall.bind(0x12085, 0xe65e6b28, 0x10, 0x0, 0x0)
       	/usr/local/Cellar/go/1.7/libexec/src/syscall/syscall_linux_386.go:258 +0x61
syscall.Bind(0x12085, 0x8408ff0, 0xe65e6b20, 0x0, 0x0)
       	/usr/local/Cellar/go/1.7/libexec/src/syscall/syscall_unix.go:221 +0x66
net.(*netFD).dial(0xe65d55c0, 0x840b680, 0xe65d5580, 0x840c100, 0x187d03c0, 0x840c100, 0xe65e6b00, 0x0, 0x0)
       	/usr/local/Cellar/go/1.7/libexec/src/net/sock_posix.go:127 +0xca
net.socket(0x840b680, 0xe65d5580, 0x8304020, 0x3, 0x2, 0x1, 0x0, 0x0, 0x840c100, 0x187d03c0, ...)
       	/usr/local/Cellar/go/1.7/libexec/src/net/sock_posix.go:89 +0x308
net.internetSocket(0x840b680, 0xe65d5580, 0x8304020, 0x3, 0x840c100, 0x187d03c0, 0x840c100, 0xe65e6b00, 0x1, 0x0, ...)
       	/usr/local/Cellar/go/1.7/libexec/src/net/ipsock_posix.go:158 +0xd0
net.doDialTCP(0x840b680, 0xe65d5580, 0x8304020, 0x3, 0x187d03c0, 0xe65e6b00, 0x0, 0x0, 0x0)
       	/usr/local/Cellar/go/1.7/libexec/src/net/tcpsock_posix.go:58 +0x98
net.dialTCP(0x840b680, 0xe65d5580, 0x8304020, 0x3, 0x187d03c0, 0xe65e6b00, 0xe11d2f21, 0x0, 0x0)
       	/usr/local/Cellar/go/1.7/libexec/src/net/tcpsock_posix.go:54 +0xa4
net.dialSingle(0x840b680, 0xe65d5580, 0xe6479db0, 0x840a650, 0xe65e6b00, 0x0, 0x0, 0x0, 0x0)
       	/usr/local/Cellar/go/1.7/libexec/src/net/dial.go:501 +0x5e0
net.dialSerial(0x840b680, 0xe65d5580, 0xe6479db0, 0xe5effe18, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
       	/usr/local/Cellar/go/1.7/libexec/src/net/dial.go:469 +0x7b3
net.(*Dialer).DialContext(0x1870a900, 0x840b680, 0xe65d5580, 0x8304020, 0x3, 0x187d02ec, 0x12, 0x0, 0x0, 0x0, ...)
       	/usr/local/Cellar/go/1.7/libexec/src/net/dial.go:351 +0x939
net.(*Dialer).Dial(0x1870a900, 0x8304020, 0x3, 0x187d02ec, 0x12, 0x0, 0x0, 0x0, 0x0)
       	/usr/local/Cellar/go/1.7/libexec/src/net/dial.go:282 +0x7e
net.(*Dialer).Dial-fm(0x8304020, 0x3, 0x187d02ec, 0x12, 0x0, 0x0, 0x0, 0x0)
       	/Users/tomas/go/src/github.com/tsenart/vegeta/lib/attack.go:61 +0x58
net/http.(*Transport).dial(0x1877e5a0, 0x840b640, 0x1870e1bc, 0x8304020, 0x3, 0x187d02ec, 0x12, 0x0, 0x0, 0x0, ...)
       	/usr/local/Cellar/go/1.7/libexec/src/net/http/transport.go:824 +0xbb
net/http.(*Transport).dialConn(0x1877e5a0, 0x840b640, 0x1870e1bc, 0x0, 0x187d02e5, 0x4, 0x187d02ec, 0x12, 0xcf5f1075, 0x0, ...)
       	/usr/local/Cellar/go/1.7/libexec/src/net/http/transport.go:962 +0x199a
net/http.(*Transport).getConn.func4(0x1877e5a0, 0x840b640, 0x1870e1bc, 0x5b9c2a40, 0x5be62b40)
       	/usr/local/Cellar/go/1.7/libexec/src/net/http/transport.go:880 +0x48
created by net/http.(*Transport).getConn
       	/usr/local/Cellar/go/1.7/libexec/src/net/http/transport.go:882 +0x3a0
```

Command used
```
echo "POST http://myip:8092" | ./vegeta attack -body=msg1.json -duration=60s -rate=70000 -keepalive=false -timeout=240s | tee results.bin | ./vegeta report
```

**Comment by tsenart** [comment]
Hello Asaf,

First of all, Vegeta wasn't designed to produce that kind of load with a single process. However, I'd be glad to see that it could! You're likely hitting resource limits of some kind but it's not clear from the stack trace you posted exactly which.

Do you have more information from that stack trace? The panic cause seems to be missing.

**Comment by aidylewis** [comment]
@asafm Did you actually get near to 70,000 r/s? Is that Go 1.7.? Anyway, at that rate distribute using pdsh or python's fabric or something. I think you can pass a number of report binaries into the report subcommand.
