### ISSUE TITLE
TestAttackDuration test fails in Arch chroot build environment

### ISSUE THREAD

**Issue by anatol** [tsenart/vegeta#355]
I am trying to compile/install version 12.1.0 in Arch chroot environment (that's a clean version of Arch Linux with minimum set of packages). Build is fine but one of the tests is flaky and fails ~ 5/6 of runs:

```
ok  	github.com/tsenart/vegeta	0.019s
?   	github.com/tsenart/vegeta/internal/cmd/echosrv	[no test files]
?   	github.com/tsenart/vegeta/internal/cmd/jsonschema	[no test files]
# github.com/tsenart/vegeta/lib/lttb.test
loadinternal: cannot find runtime/cgo
ok  	github.com/tsenart/vegeta/internal/resolver	0.029s
panic: Fail in goroutine after TestAttackDuration has completed

goroutine 3521 [running]:
testing.(*common).Fail(0xc000134200)
	/usr/lib/go/src/testing/testing.go:546 +0x137
testing.(*common).FailNow(0xc000134200)
	/usr/lib/go/src/testing/testing.go:568 +0x2d
testing.(*common).Fatal(0xc000134200, 0xc0000357c0, 0x1, 0x1)
	/usr/lib/go/src/testing/testing.go:628 +0x71
github.com/tsenart/vegeta/lib.TestAttackDuration.func2()
	/build/vegeta/src/gopath/src/github.com/tsenart/vegeta/lib/attack_test.go:44 +0x6a
created by time.goFunc
	/usr/lib/go/src/time/sleep.go:172 +0x46
FAIL	github.com/tsenart/vegeta/lib	2.109s
ok  	github.com/tsenart/vegeta/lib/lttb	7.019s
ok  	github.com/tsenart/vegeta/lib/plot	2.252s
```

**Comment by tsenart** [comment]
It seems to me that  `loadinternal: cannot find runtime/cgo` is the problem. Please use the [Bug Report](https://github.com/tsenart/vegeta/issues/new?labels=&template=bug_report.md) issue template so that we can track this down.
